Added URL generation for accessing CDN
liam-mh/SAaD_8 pull request #10
Opened 2024-11-15 15:30 UTC by LewisWorton

2024-11-15 15:44 UTC, liam-mh requested changes

2024-11-15 15:44 UTC, liam-mh commented on Application/client/src/services/memberService.js
Can this be placed in its own file, say mediaService or something? Unsure if it being in memberService makes sense as it is to do with our media items

2024-11-15 15:44 UTC, liam-mh commented on Application/api-gateway/middleware/forwardRequestMiddleware.js
why was this default value changed?

2024-11-15 15:55 UTC, LewisWorton commented on Application/api-gateway/middleware/forwardRequestMiddleware.js
Quick test I did, forgot to change it back before PR so did it on browser.

2024-11-16 15:41 UTC, liam-mh approved these changes
thanks

2024-11-16 15:43 UTC, merged